const stepsTATJourneyCrpLs = [
  {
      tat: "TAT 1",
      color: "#0f99ef",
      text: "(10 Days) to respond the ticket missed ticket type changed to escalated ticket",
      date: "",
      icon: "",
      textId: "System Processed",
      agentName: "",
      ticket: "",
      status: "",
      ticketStatus: "",
      smsText: "",
      ageing: "0-10 days",
    },
    {
      tat: "TAT 2",
      color: "#eb0c7b",
      text: "(15 Days) to respond the ticket missed ticket type changed to escalated ticket",
      date: "",
      icon: "",
      textId: "System Processed",
      agentName: "",
      ticket: "",
      status: "",
      ticketStatus: "",
      smsText: "",
      ageing: "11-15 days",
    },
    {
      tat: "TAT 3",
      color: "#b94e00",
      text: "(20 Days) to respond the ticket missed ticket type changed to escalated ticket",
      date: "",
      icon: "",
      textId: "System Processed",
      agentName: "",
      ticket: "",
      status: "",
      ticketStatus: "",
      smsText: "",
      ageing: "16-20 days",
    },

    {
      tat: "TAT 4",
      color: "#f06d1a",
      text: "(20 > Days) to respond the ticket missed ticket type changed to escalated ticket",
      date: "",
      icon: "",
      textId: "System Processed",
      agentName: "",
      ticket: "",
      status: "",
      ticketStatus: "",
      smsText: "",
      ageing: "20> days",
    },
];



 const stepsTATJourneyGrv = [
    {
      tat: "TAT 1",
      color: "#0f99ef",
      text: "(3 Days) to respond the ticket missed ticket type changed to escalated ticket",
      date: "",
      icon: "",
      textId: "System Processed",
      agentName: "",
      ticket: "",
      status: "",
      ticketStatus: "",
      smsText: "",
      ageing: "0-3 days",
    },
    {
      tat: "TAT 2",
      color: "#eb0c7b",
      text: "(7 Days) to respond the ticket missed ticket type changed to escalated ticket",
      date: "",
      icon: "",
      textId: "System Processed",
      agentName: "",
      ticket: "",
      status: "",
      ticketStatus: "",
      smsText: "",
      ageing: "4-7 days",
    },
    {
      tat: "TAT 3",
      color: "#b94e00",
      text: "(12 Days) to respond the ticket missed ticket type changed to escalated ticket",
      date: "",
      icon: "",
      textId: "System Processed",
      agentName: "",
      ticket: "",
      status: "",
      ticketStatus: "",
      smsText: "",
      ageing: "8-12 days",
    },
    {
      tat: "TAT 4",
      color: "#6908b1",
      text: "(15 Days) to respond the ticket missed ticket type changed to escalated ticket",
      date: "",
      icon: "",
      textId: "System Processed",
      agentName: "",
      ticket: "",
      status: "",
      ticketStatus: "",
      smsText: "",
      ageing: "13-15 days",
    },
    {
      tat: "TAT 5",
      color: "#f06d1a",
      text: "(16 > Days) to respond the ticket missed ticket type changed to escalated ticket",
      date: "",
      icon: "",
      textId: "System Processed",
      agentName: "",
      ticket: "",
      status: "",
      ticketStatus: "",
      smsText: "",
      ageing: "16> days",
    },
]
